# Generated by Django 2.0.2 on 2018-10-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='claveUt',
        ),
        migrations.AddField(
            model_name='director',
            name='claveUt',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='directores.Ut'),
            preserve_default=False,
        ),
    ]
